stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "dungxbuns/vdt-lab-backend"
  DOCKER_TLS_CERTDIR: ""

image: docker:latest

services:
  - docker:19.03.12-dind

before_script:
  - apk add --no-cache curl jq
  - docker info
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  script:
    - |
      # Fetch current tags from Docker Hub
      TAGS=$(curl -s -u "$DOCKER_USERNAME:$DOCKER_PASSWORD" "https://hub.docker.com/v2/repositories/$DOCKER_IMAGE/tags" | jq '.count')
      echo "Current tags count: $TAGS"
      
      # Calculate new tag
      NEW_TAG="v$((TAGS + 1))"
      echo "New tag: $NEW_TAG"

      # Build and push Docker image
      docker build -t $DOCKER_IMAGE:$NEW_TAG .
      docker push $DOCKER_IMAGE:$NEW_TAG
      echo "NEW_TAG=$NEW_TAG" > .env

  artifacts:
    reports:
      dotenv: .env

deploy:
  stage: deploy
  script:
    - export $(cat .env | xargs)
    - git clone https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/dungbun31/ks8-config-api.git
    - cd ks8-config-api
    - |
      echo "New tag: $NEW_TAG"
    - |
      sed -i "s/tag: .*/tag: '$NEW_TAG'/" values.yaml
    - git config --global user.email "gitlab-ci@your-domain.com"
    - git config --global user.name "GitLab CI"
    - git add values.yaml
    - git commit -m "Update image tag to $NEW_TAG"
    - git push origin main
  only:
    - main
