apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 8080 
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.nameOverride | default .Chart.Name }}
